#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jul 21 01:33:20 KST 2025
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim cnn_top_tb_behav -key {Behavioral:sim_1:Functional:cnn_top_tb} -tclbatch cnn_top_tb.tcl -view /home/goeun/gitHub/Braille_generator_FPGA/1.line_buffer_kernel_5by5_convolution/project_1/cnn_top_tb_behav.wcfg -view /home/goeun/gitHub/Braille_generator_FPGA/1.line_buffer_kernel_5by5_convolution/project_1/cnn_top_tb_behav1.wcfg -log simulate.log"
xsim cnn_top_tb_behav -key {Behavioral:sim_1:Functional:cnn_top_tb} -tclbatch cnn_top_tb.tcl -view /home/goeun/gitHub/Braille_generator_FPGA/1.line_buffer_kernel_5by5_convolution/project_1/cnn_top_tb_behav.wcfg -view /home/goeun/gitHub/Braille_generator_FPGA/1.line_buffer_kernel_5by5_convolution/project_1/cnn_top_tb_behav1.wcfg -log simulate.log

